apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: micro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      serviceAccountName: product-service-sa
      containers:
        - name: product-service
          image: 111111111111.dkr.ecr.us-east-1.amazonaws.com/product-service:latest
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: common-secrets
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: micro
spec:
  selector:
    app: product-service
  ports:
    - port: 80
      targetPort: 8000

