apiVersion: v1
kind: Secret
metadata:
  name: common-secrets
  namespace: micro
type: Opaque
stringData:
  DB_URL: "CHANGE_ME"
  JWT_SECRET: "CHANGE_ME"
  SMTP_HOST: "smtp.example.com"
  SMTP_USER: "user@example.com"
  SMTP_PASS: "CHANGE_ME"
