# kube-prometheus-stack values

grafana:
  adminPassword: admin
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: false
  defaultDashboardsEnabled: true
  grafana.ini:
    server:
      root_url: %(protocol)s://%(domain)s/
      serve_from_sub_path: true
  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki.monitoring:3100
      isDefault: false

prometheus:
  service:
    type: ClusterIP
  prometheusSpec:
    retention: 7d
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi

alertmanager:
  enabled: true
  alertmanagerSpec:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 300m
        memory: 512Mi

