groups:
  - name: instance-health
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: Instance down
          description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 2 minutes.'

